routes/admin.php
<?php

/**
 * 总后台的路由文件
 */

//后台的路由组
Route::group(['prefix'=>'admin'],function (){

    //登陆显示页面
    Route::get('/login','\App\Admin\Controllers\LoginController@index');
    //登陆处理逻辑
    Route::post('/login','\App\Admin\Controllers\LoginController@login');
    //登出处理
    Route::get('/logout','\App\Admin\Controllers\LoginController@logout');
    Route::group(['middleware'=>'auth:admin'],function(){

        //后台首页
        Route::get('/home','\App\Admin\Controllers\HomeController@index');

        //使用门卫 进行权限验证  这个模块是系统管理模块  包含 管理员 角色 权限 的功能
//        Route::group(['middleware'=>'can:system'],function (){
            //管理员模块
            Route::get('/users','\App\Admin\Controllers\UserController@index');//管理员列表
            Route::get('/users/create','\App\Admin\Controllers\UserController@create');//管理员新增页面
            Route::post('/users/store','\App\Admin\Controllers\UserController@store');//管理员新增验证逻辑
            Route::get('/users/{user}/role','\App\Admin\Controllers\UserController@role');//管理员角色关联页面
            Route::post('/users/{user}/role','\App\Admin\Controllers\UserController@storeRole');//处理管理员分配角色逻辑

            //权限
            Route::get('/permissions','\App\Admin\Controllers\PermissionController@index');//权限列表
            Route::get('/permissions/create','\App\Admin\Controllers\PermissionController@create');//创建权限页面
            Route::post('/permissions/store','\App\Admin\Controllers\PermissionController@store');//处理创建权限逻辑

            //角色相关
            Route::get('/roles','\App\Admin\Controllers\RoleController@index');//角色列表
            Route::get('/roles/create','\App\Admin\Controllers\RoleController@create');//创建角色页面
            Route::post('/roles/store','\App\Admin\Controllers\RoleController@store');//处理创建角色逻辑
            Route::get('/roles/{role}/permission','\App\Admin\Controllers\RoleController@permission');//给角色分配权限页面
            Route::post('/roles/{role}/permission','\App\Admin\Controllers\RoleController@storePermission');//处理分配权限的逻辑
//        });

        //使用门卫 进行权限验证  这个模块是文章管理模块
//        Route::group(['middleware'=>'can:post'],function (){
            //文章审核模块
            Route::get('/posts','\App\Admin\Controllers\PostController@index');//获取待审核文章
            Route::post('/posts/{post}/status','\App\Admin\Controllers\PostController@status');//审核文章逻辑处理
//        });

        //使用门卫 进行权限验证  这个模块是通知管理模块  只用到 列表页 增加  不需要删除
//        Route::group(['middleware'=>'can:notice'],function (){
            Route::resource('notices','\App\Admin\Controllers\NoticeController',[
                'only'=>['index','create','store']
            ]);
//        });

        //使用门卫 进行权限验证  这个模块是专题管理模块
//        Route::group(['middleware' => 'can:topic'], function(){
            Route::resource('topics', '\App\Admin\Controllers\TopicController', ['only' => [
                'index', 'create', 'store', 'destroy'
            ]]);
//        });










    });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * 用户模块
 */
//用户模块
Route::get('/',function(){
   return redirect('/login');
});
//注册页面
Route::get('/register','RegisterController@index');
//注册的处理
Route::post('/register','RegisterController@register');
//登陆页面
Route::get('/login','LoginController@index')->name('login');
//登陆的处理
Route::post('/login','LoginController@login');

Route::group(['middleware'=>'auth:user'],function(){
    //登出
    Route::get('/logout','LoginController@logout');


    //个人设置页面
    Route::get('/user/me/setting','UserController@setting');
    //个人设置处理
    Route::post('/user/{user}/setting','UserController@settingStore');


    //文章列表页
    Route::get('/posts','PostController@index');
    //文章详情页
    Route::get('/posts/{post}','PostController@show');
    //创建文章 -- 页面
    Route::get('/post/create','PostController@create');
    //创建文章 -- 保存
    Route::post('/posts','PostController@store');
    //编辑文章 --读取数据
    Route::get('/posts/{post}/edit','PostController@edit');
    //编辑文章 --保存
    Route::put('/posts/{post}','PostController@update');
    //删除文章
    Route::get('/posts/{post}/delete','PostController@delete');
    //图片上传路由
    Route::post('/posts/image/upload','PostController@imageUpload');
    //提交评论
    Route::post('/posts/{post}/comment','PostController@comment');


    //点赞
    Route::get('/posts/{post}/zan','PostController@zan');
    //取消赞
    Route::get('/posts/{post}/unzan','PostController@unzan');


    //个人中心
    Route::get('/user/{user}','UserController@show');
    //对某个用户进行关注
    Route::post('/user/{user}/fan','UserController@fan');
    //取消关注
    Route::post('/user/{user}/unfan','UserController@unfan');


    //专题详情页
    Route::get('/topic/{topic}','TopicController@show');
    //专题投稿
    Route::post('/topic/{topic}/submit','TopicController@submit');


    //通知模块
    Route::get('/notices','NoticeController@index');

});

include_once "admin.php";

app/User.php
<?php

namespace App;

use App\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{

    protected $fillable = [
        'name','email','password'
    ];

    //获取当前用户有多少文章
    public function posts(){
        return $this->hasMany('App\Post','user_id','id');
    }

    //获取当前用户拥有多少粉丝--当前用户是被关注的 所以star_i 等于当前用户的id
    public function fans(){
        return $this->hasMany('App\Fan','star_id','id');
    }

    //获取当前用户关注了哪些人---当前用户是粉丝 所以 fan_id 等于当前用户的id
    public function stars(){
        return $this->hasMany('App\Fan','fan_id','id');
    }

    /**
     * 当前用户 需要关注 某个用户
     * 参数  被关注的用户id
     */
    public function doFan($uid)
    {
        $fan = new Fan();
        $fan->star_id = $uid;//传入的id就是等于粉丝表的被关注id
        //进行保存
        return $this->stars()->save($fan);
    }

    /**
     * 取消关注
     * 参数  被关注的用户id
     */
    public function doUnfan($uid){
        $fan = new Fan();
        $fan->star_id = $uid;//传入的id就是等于粉丝表的被关注id
        //进行删除
        return $this->stars()->delete($fan);
    }

    /**
     * @param $uid
     * @return mixed
     * 当前用户是否被人关注 并算出总数
     */
    public function hasFan($uid){
        return $this->fans()->where('fan_id',$uid)->count();
    }

    /**
     * 当前用户是否关注某个用户  并算出总数
     */
    public function hasStar($uid){
        return $this->stars()->where('star_id',$uid)->count();
    }

    //用户收到的通知 一个用户收到多个通知 一个通知发给多个用户  多对多关系
    public function notices(){
        // 关联模型 关联表 在关联表中的外键  要取的对象  然后要取的数据
        return  $this->belongsToMany(\App\Notice::class,'user_notice','user_id','notice_id')->withPivot(['user_id','notice_id']);
    }

    //给用户发送通知
    public function addNotice($notice){
        return $this->notices()->save($notice);//save是增加 detach是删除
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    //个人中心页面
    public function show(User $user){
        //获取个人信息  个人的关注 粉丝 文章数
        $user = User::withCount(['fans','stars','posts'])->find($user->id);
        //个人的文章列表 取出最新创建的十条
        $posts = $user->posts()->orderBy('created_at','desc')->take(10)->get();
        //获取这个人关注的用户 以及这个用户下的 关注数 粉丝数 文章数
        $stars = $user->stars;
        $susers = User::whereIn('id',$stars->pluck('star_id'))->withCount(['fans','stars','posts'])->get();
        //获取这个人的粉丝 以及这个粉丝下的  关注数 粉丝数 文章数
        $fans = $user->fans;
        $fusers = User::whereIn('id',$fans->pluck('fan_id'))->withCount(['fans','stars','posts'])->get();
        return view('user/show',compact('user','posts','susers','fusers'));
    }

    //关注用户
    public function fan(User $user){
        $me = Auth::user();
        $me->doFan($user->id);
        return [
            'error'=>0,
            'msg'=>'关注成功'
        ];
    }

    //取消关注
    public function unfan(User $user){
        $me = Auth::user();
        $me->doUnfan($user->id);
        return [
            'error'=>0,
            'msg'=>'取关成功'
        ];
    }
    //个人设置页面
    public function setting(){
        $me = Auth::user();
        return view('user/setting', compact('me'));
    }
    //个人设置处理
    public function settingStore(Request $request,User $user){

        if ($request->file('avatar')) {
            $path = $request->file('avatar')->storePublicly(md5(\Auth::id() . time()));
            $user->avatar = "/storage/". $path;
        }

        $user->save();
        return back();
    }
}

resources/views/user/setting.blade.php
@extends("layout.main")

@section("content")

    <div class="col-sm-8 blog-main">
        <form class="form-horizontal" action="/user/{{\Auth::id()}}/setting" method="POST" enctype="multipart/form-data">
            <input type="hidden" name="_token" value="{{csrf_token()}}">
            <div class="form-group">
                <label class="col-sm-2 control-label">用户名</label>
                <div class="col-sm-10">
                    <input class="form-control" name="name" readonly type="text" value="{{$me->name}}">

                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">头像</label>
                <div class="col-sm-2">
                    <input class=" file-loading preview_input" type="file" value="用户名" style="width:250px" name="avatar">
                    <img width="100"  class="preview_img" src="{{$me->avatar}}" alt="" class="img-rounded" style="border-radius:500px;margin-top: 10px;">
                </div>
            </div>
            <button type="submit" class="btn btn-default">修改</button>
        </form>
        <br>

    </div>

@endsection

resources/views/user/show.blade.php
@extends("layout.main")

@section("content")

    <div class="col-sm-8">
        <blockquote>
            <p><img src="{{$user->avatar}}" alt="" class="img-rounded" style="border-radius:500px; height: 40px"> {{$user->name}}
            </p>


            <footer>关注：{{$user->stars_count}}｜粉丝：{{$user->fans_count}}｜文章：{{$user->posts_count}}</footer>
            @include('user.badges.like', ['target_user' => $user])
        </blockquote>
    </div>
    <div class="col-sm-8 blog-main">
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="true">文章</a></li>
                <li class=""><a href="#tab_2" data-toggle="tab" aria-expanded="false">关注</a></li>
                <li class=""><a href="#tab_3" data-toggle="tab" aria-expanded="false">粉丝</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="tab_1">
                    @foreach($posts as $post)
                        <div class="blog-post" style="margin-top: 30px">
                            <?php \Carbon\Carbon::setLocale('zh');?>
                            <p class=""><a href="/user/{{$post->user_id}}">{{$post->user->name}}</a> {{$post->created_at->diffForHumans()}}</p>
                            <p class=""><a href="/posts/{{$post->id}}" >{{$post->title}}</a></p>


                            <p>{!! str_limit($post->content, 100, '...') !!}</p>
                        </div>
                    @endforeach
                </div>
                <!-- /.tab-pane -->
                <div class="tab-pane" id="tab_2">
                    @foreach($susers as $suser)
                        <div class="blog-post" style="margin-top: 30px">
                            <p class="">{{$suser->name}}</p>
                            <p class="">关注：{{$suser->stars_count}}| 粉丝：{{$suser->fans_count}}｜ 文章：{{$suser->posts_count}}</p>

                            @include('user.badges.like',['target_user'=>$user])

                        </div>
                    @endforeach
                </div>
                <!-- /.tab-pane -->
                <div class="tab-pane" id="tab_3">
                    @foreach($fusers as $fan)
                        <div class="blog-post" style="margin-top: 30px">
                            <p class="">{{$fan->name}}</p>
                            <p class="">关注：{{$fan->stars_count}} | 粉丝：{{$fan->fans_count}}｜ 文章：{{$fan->posts_count}}</p>
                            @include('user.badges.like',['target_user'=>$user])
                        </div>
                    @endforeach
                </div>
                <!-- /.tab-pane -->
            </div>
            <!-- /.tab-content -->
        </div>


    </div><!-- /.blog-main -->


@endsection