routes/admin.php
<?php

/**
 * 总后台的路由文件
 */

//后台的路由组
Route::group(['prefix'=>'admin'],function (){

    //登陆显示页面
    Route::get('/login','\App\Admin\Controllers\LoginController@index');
    //登陆处理逻辑
    Route::post('/login','\App\Admin\Controllers\LoginController@login');
    //登出处理
    Route::get('/logout','\App\Admin\Controllers\LoginController@logout');
    Route::group(['middleware'=>'auth:admin'],function(){

        //后台首页
        Route::get('/home','\App\Admin\Controllers\HomeController@index');

        //使用门卫 进行权限验证  这个模块是系统管理模块  包含 管理员 角色 权限 的功能
//        Route::group(['middleware'=>'can:system'],function (){
            //管理员模块
            Route::get('/users','\App\Admin\Controllers\UserController@index');//管理员列表
            Route::get('/users/create','\App\Admin\Controllers\UserController@create');//管理员新增页面
            Route::post('/users/store','\App\Admin\Controllers\UserController@store');//管理员新增验证逻辑
            Route::get('/users/{user}/role','\App\Admin\Controllers\UserController@role');//管理员角色关联页面
            Route::post('/users/{user}/role','\App\Admin\Controllers\UserController@storeRole');//处理管理员分配角色逻辑

            //权限
            Route::get('/permissions','\App\Admin\Controllers\PermissionController@index');//权限列表
            Route::get('/permissions/create','\App\Admin\Controllers\PermissionController@create');//创建权限页面
            Route::post('/permissions/store','\App\Admin\Controllers\PermissionController@store');//处理创建权限逻辑

            //角色相关
            Route::get('/roles','\App\Admin\Controllers\RoleController@index');//角色列表
            Route::get('/roles/create','\App\Admin\Controllers\RoleController@create');//创建角色页面
            Route::post('/roles/store','\App\Admin\Controllers\RoleController@store');//处理创建角色逻辑
            Route::get('/roles/{role}/permission','\App\Admin\Controllers\RoleController@permission');//给角色分配权限页面
            Route::post('/roles/{role}/permission','\App\Admin\Controllers\RoleController@storePermission');//处理分配权限的逻辑
//        });

        //使用门卫 进行权限验证  这个模块是文章管理模块
//        Route::group(['middleware'=>'can:post'],function (){
            //文章审核模块
            Route::get('/posts','\App\Admin\Controllers\PostController@index');//获取待审核文章
            Route::post('/posts/{post}/status','\App\Admin\Controllers\PostController@status');//审核文章逻辑处理
//        });

        //使用门卫 进行权限验证  这个模块是通知管理模块  只用到 列表页 增加  不需要删除
//        Route::group(['middleware'=>'can:notice'],function (){
            Route::resource('notices','\App\Admin\Controllers\NoticeController',[
                'only'=>['index','create','store']
            ]);
//        });

        //使用门卫 进行权限验证  这个模块是专题管理模块
//        Route::group(['middleware' => 'can:topic'], function(){
            Route::resource('topics', '\App\Admin\Controllers\TopicController', ['only' => [
                'index', 'create', 'store', 'destroy'
            ]]);
//        });










    });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * 用户模块
 */
//用户模块
Route::get('/',function(){
   return redirect('/login');
});
//注册页面
Route::get('/register','RegisterController@index');
//注册的处理
Route::post('/register','RegisterController@register');
//登陆页面
Route::get('/login','LoginController@index')->name('login');
//登陆的处理
Route::post('/login','LoginController@login');

Route::group(['middleware'=>'auth:user'],function(){
    //登出
    Route::get('/logout','LoginController@logout');


    //个人设置页面
    Route::get('/user/me/setting','UserController@setting');
    //个人设置处理
    Route::post('/user/{user}/setting','UserController@settingStore');


    //文章列表页
    Route::get('/posts','PostController@index');
    //文章详情页
    Route::get('/posts/{post}','PostController@show');
    //创建文章 -- 页面
    Route::get('/post/create','PostController@create');
    //创建文章 -- 保存
    Route::post('/posts','PostController@store');
    //编辑文章 --读取数据
    Route::get('/posts/{post}/edit','PostController@edit');
    //编辑文章 --保存
    Route::put('/posts/{post}','PostController@update');
    //删除文章
    Route::get('/posts/{post}/delete','PostController@delete');
    //图片上传路由
    Route::post('/posts/image/upload','PostController@imageUpload');
    //提交评论
    Route::post('/posts/{post}/comment','PostController@comment');


    //点赞
    Route::get('/posts/{post}/zan','PostController@zan');
    //取消赞
    Route::get('/posts/{post}/unzan','PostController@unzan');


    //个人中心
    Route::get('/user/{user}','UserController@show');
    //对某个用户进行关注
    Route::post('/user/{user}/fan','UserController@fan');
    //取消关注
    Route::post('/user/{user}/unfan','UserController@unfan');


    //专题详情页
    Route::get('/topic/{topic}','TopicController@show');
    //专题投稿
    Route::post('/topic/{topic}/submit','TopicController@submit');


    //通知模块
    Route::get('/notices','NoticeController@index');

});

include_once "admin.php";

app/Topic.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Topic extends Model
{
    protected  $fillable = ['name'];
    //获取属于专题的文章  也就是专题和文章的关系  多对多关系
    pubLic function posts(){
        return $this->belongsToMany('\App\Post','post_topics','topic_id','post_id');

    }
    //获取文章数
    public function postTopics(){
        return $this->hasMany('\App\PostTopic');
    }
}

app/Http/Controllers/TopicController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use App\PostTopic;
use App\Topic;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class TopicController extends Controller
{
    //专题详情页
    public function show(Topic $topic){
        //专题下的文章数
        $topic = Topic::withCount('postTopics')->find($topic->id);

        //当前专题的文章列表
        $posts = $topic->posts()->orderBy('created_at','desc')->take(10)->get();

        //属于当前用户的文章 但是没有投稿
        $myposts = \App\Post::authorBy(Auth::id())->topicNotBy($topic->id)->get();
        return view('topic/show',compact('topic','posts','myposts'));
    }

    //专题投稿
    public function submit(Topic $topic){

        //验证
        $this->validate(\request(),[
           'post_ids'=>'required|array'
        ]);
        //处理
        $post_ids = request('post_ids');
        $topic_id = $topic->id;
        //编辑数组
        foreach($post_ids  as $post_id){
            PostTopic::firstOrCreate(compact('topic_id','post_id'));
        }
        //返回
        return back();
    }
}

resources/views/topic/show.blade.php
@extends('layout.main')
@section('content')
        <div class="col-sm-8">
            <blockquote>
                <p>{{$topic->name}}</p>
{{--                此时这里的驼峰要转成全部小写--}}
                <footer>文章：{{$topic->post_topics_count}}</footer>
                <button class="btn btn-default topic-submit"  data-toggle="modal" data-target="#topic_submit_modal" topic-id="{{$topic->id}}"  type="button">投稿</button>
            </blockquote>
        </div>
        <div class="modal fade" id="topic_submit_modal" tabindex="-1" role="dialog" >
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">我的文章</h4>
                    </div>
                    <div class="modal-body">
                        <form action="/topic/{{$topic->id}}/submit" method="post">
                            <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>" />
                            @foreach($myposts as $post)
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="post_ids[]" value="{{$post->id}}">
                                        {{$post->title}}
                                    </label>
                                </div>
                            @endforeach
                            <button type="submit" class="btn btn-default">投稿</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-8 blog-main">
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="true">文章</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="tab_1">
                        @foreach($posts as $post)
                        <div class="blog-post" style="margin-top: 30px">
                            <p class=""><a href="/user/{{$post->user->id}}">{{$post->user->name}}</a> {{$post->created_at->diffForHumans()}}</p>
                            <p class=""><a href="/posts/{{$post->id}}" >{{$post->title}}</a></p>
                            <p>{!! str_limit($post->content,100,'...') !!}</p>
                        </div>
                        @endforeach
                    </div>

                </div>
                <!-- /.tab-content -->
            </div>


        </div><!-- /.blog-main -->
@endsection